---
cpe:
  ip: 192.168.254.3
  port: '30005'
  path: "/"
  username: KAOBLOi
  password: KAOBLOi
acs:
  name: Rails ACS
  username: ACSOi
  password: ACSOi
trxml:
  path: config/xml/
  xmls:
    tr-069: tr-069-1-0-0-full.xml
    tr-098: tr-098-1-8-0-full.xml
    tr-143: tr-143-1-0-2-full.xml
    tr-157: tr-157-1-3-0-full.xml
    tr-181: tr-181-2-11-0-full.xml
